### ISSUE TITLE
Rework translations

### ISSUE THREAD

**Issue by jbrooksuk** [CachetHQ/Cachet#3726]
Translations are hard to manage and visualise as we use the short translation keys. Instead, we should migrate to the string translations https://laravel.com/docs/5.8/localization#using-translation-strings-as-keys

**To-do:**

- [ ] Convert **all** existing translations to their JSON counterpart.
- [ ] Replace `trans` calls with the `__` method and full string.
- [ ] Upload new translation JSON strings.

**Comment by jbrooksuk** [comment]
Thank you for your input on Cachet 2.x. We are shifting our attention and resources to Cachet 3.x and will no longer be supporting the 2.x version. If your feedback or issue is relevant to the 3.x series, we encourage you to engage with the new branch.

For more information on the Cachet rebuild and our plans for 3.x, you can read the announcement [here](https://github.com/CachetHQ/Cachet/discussions/4342).

We appreciate your understanding and look forward to your contributions to the new version.
