### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by jbrooksuk** [cachethq/cachet#61]
The First Release milestone is coming up (due 22nd December). If you're new to Cachet or unsure of what work needs to be done towards getting this first release out, here is a rundown of what needs to be done.
- [x] Design (#2) - @Ehesp has mocked up the dashboard within the **[ui](/cachethq/ui) repository**. This needs converting into HTML and CSS as a reusable set of components as the design will be used for the dashboard, setup and login screens.
- [x] API (#3, #25) - The API is almost finished however we need to add authorization for use within the Cachet app itself. This could be achieved with the app token.
- [x] Setup page (#12)
- [ ] Once the design is complete we'll need to be able to create components, incidents, metrics and users from the dashboard.

Essentially this is all that is needed for a first release. We'll be able to refine and add more features later on.
